const PATH = {
    EMPTY: '',
    ROOT: '/',
    DASHBOARD: '/admin',
    LOGIN: '/admin/login',
    USER_LIST: '/admin/users',
    USER_UPDATE: '/admin/users/:id',
    PRODUCT_LIST: '/admin/products',
    PRODUCT_CREATE: '/admin/products/create',
    CATEGORY_LIST: '/admin/categories',
    BRAND_LIST: '/admin/brands',
    SUPPLIER_LIST: '/admin/suppliers',
    SUPPLIER_CREATE: '/admin/suppliers/create',
    SUPPLIER_UPDATE: '/admin/suppliers/:id',
    PURCHASE_LIST: '/admin/purchases',
    PURCHASE_CREATE: '/admin/purchases/create',
    PURCHASE_UPDATE: '/admin/purchases/:id',
    WAREHOURSE_LIST: '/admin/warehouses',
    PRICE_PLAN_LIST: '/admin/price-plans',
    PRICE_PLAN_LIST_CREATE: '/admin/price-plans/create',
    PRICE_PLAN_LIST_HISTORY: '/admin/price-plans/history',
    PRODUCT_EDIT: '/admin/products/:id',
    PRODUCT_SALE: '/admin/products/sale',
    ORDER_LIST: '/admin/orders',
    ORDER_DETAIL: '/admin/orders/:id',
    RETURN_ORDERS: '/admin/return-orders',
    REVENUE_SALE: '/admin/revenue-sale',
    REVENUE_WAREHOUSE: '/admin/revenue-warehouse'
}
export default PATH
